openapi: 3.0.1
info:
  title: Service - short link
  version: 1.0.0
paths:
  /api/v1/short_links:
    post:
      tags:
        - Short link API
      summary: Creates a new short link
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLinkParams'
      responses:
        '201':
          description: Short link is created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortLinks'
        '422':
          description: Unprocessable entity
    get:
      tags:
        - Short link API
      summary: Lists of all short links with statistics
      responses:
        '200':
          description: A list of short links
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortLinksArray'
  /api/v1/short_links/{id}:
    parameters:
      - name: id
        in: path
        description: ID of the link
        required: true
        schema:
          type: integer
      - name: password
        in: query
        description: Password to authenticate the operation
        required: true
        schema:
          type: string
    delete:
      tags:
        - Short link API
      summary: Remove a short link
      responses:
        '200':
          description: Remove a short link
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseRemoved'
        '422':
          description: Unprocessable entity
components:
  schemas:
    CreateLinkParams:
      type: object
      properties:
        original_url:
          type: string
          example: "https://google.com"
    ShortLinks:
      type: object
      properties:
        id:
          type: integer
          example: 1
        original_url:
          type: string
          example: "https://google.com"
        short_url:
          type: string
          example: "fc6245"
        password:
          type: string
          example: "9290e4ef4f01dc72f220"
        link_opened:
          type: integer
        link_opened_last_time_at:
          type: string
          format: date-time
          example: null
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    ResponseRemoved:
      type: object
      properties:
        message:
          type: string
          example: "Short link is deleted"
    ShortLinksArray:
      type: array
      items:
        $ref: '#/components/schemas/ShortLinks'
servers:
  - url: 'https://454c-185-143-144-159.ngrok-free.app'
  - url: 'http://localhost:3000'
